import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LassoCV


def ols_sklearn(train, test):
    # df = pd.read_csv('data/result_panel.csv', low_memory=False)  # load into the data frame
    # filter_col = [col for col in list(df) if col.startswith('x_')]
    filter_col = ['x_dem', 'x_nonwhite', 'x_noreligion']
    target = 'govt_wins'
    linear_reg = LinearRegression(normalize=True)
    linear_reg.fit(train[filter_col], train[target])
    result = pd.DataFrame(list(zip(filter_col, linear_reg.coef_)), columns=['features', 'coefficients'])
    expected_insample = train['govt_wins']
    expected_outsample = test['govt_wins']
    predicted_insample = linear_reg.predict(train[filter_col])
    predicted_outsample = linear_reg.predict(test[filter_col])
    print(result)
    print()
    print('Intercept: ' + str(linear_reg.intercept_))
    print('R-sq: ' + str(linear_reg.score(train[filter_col], train[target])))
    print('in sample mse: ' + str(np.mean((predicted_insample - expected_insample) ** 2)))
    print('out sample mse: ' + str(np.mean((predicted_outsample - expected_outsample) ** 2)))


def fit_stat_model(df, filter_col, target='govt_wins'):
    '''
    Train the model using the training data
    :return: Linear Regression with least OLS
    '''
    model = sm.OLS(df[target], df[filter_col]).fit()
    convert_textfile(model)
    return model


def convert_textfile(model):
    '''

    :param model: Takes in the model generated by the training data
    :return: saves the .txt file to output folder
    '''
    f = open('outputfiles/ols_output.txt', "w")
    f.write(str(model.summary()))
    f.close()


def test_stat_model(model, insample, outsample):
    '''
    Test the stat model on testing data
    :return: Accuracy summary
    '''
    filter_col = ['x_dem', 'x_nonwhite', 'x_noreligion']
    target = 'govt_wins'

    # In sample prediction
    ypred = model.predict(insample[filter_col])
    y_actual = insample[target]
    print('mse: (insample) ' + str(np.mean((ypred - y_actual)) ** 2))

    # Out of sample prediction
    ypred = model.predict(outsample[filter_col])
    y_actual = outsample[target]
    print('mse: (outsample) ' + str(np.mean((ypred - y_actual)) ** 2))


def lasso_for_feature_selection(df, target='govt_wins'):
    characteristics_cols = [col for col in list(df) if col.startswith('x_')]
    X, y = df[characteristics_cols].fillna(0), df[target]
    clf = LassoCV()
    sfm = SelectFromModel(clf, threshold=0.15)
    sfm.fit(X, y)
    print(sfm.transform(X).shape[1])
    print([x for (x, y) in zip(characteristics_cols, sfm.get_support()) if y == True])
